---
- hosts: all
  become: true
  become_user: root
  tasks:
  - apt: update_cache=yes cache_valid_time=3600
  - name: install packages
    apt: name={{item}} state=latest
    with_items:
      - ansible
  - name: Install docker-compose
    get_url: url=https://github.com/docker/compose/releases/download/1.8.1/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=0755
