#!/usr/bin/env bash
set -euo pipefail

if [ ! -f /usr/local/bin/brew ]; then
    echo "--> Installing Homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "--> Running brew bundle"
brew bundle
