#!/bin/bash
set -euo pipefail

# TODO - why do we have to do this.
function finish {
  mv ~/.netrc.tmp ~/.netrc
}
trap finish EXIT
echo "--> Temporarily relocating netrc"
mv ~/.netrc ~/.netrc.tmp

if [ ! -f /usr/bin/ansible-playbook ]; then
    sudo apt-get install -y software-properties-common
    sudo apt-add-repository -y ppa:ansible/ansible
    sudo apt-get update
    sudo apt-get install -y ansible
fi

ansible-playbook -i "localhost," -c local playbook.yml

rm -f playbook.retry
