#!/bin/bash
set -euo pipefail

if [ ! -f /usr/bin/ansible-playbook ]; then
    sudo apt-get install -y software-properties-common
    sudo apt-add-repository -y ppa:ansible/ansible
    sudo apt-get update
    sudo apt-get install -y ansible
fi

ansible-playbook -i "localhost," -c local playbook.yml
