#!/usr/bin/env bash
set -euo pipefail

echo "--> Setting defaults"
defaults write com.googlecode.iterm2 "PrefsCustomFolder" -string "$HOME/.config/iterm2"
defaults write com.googlecode.iterm2 "LoadPrefsFromCustomFolder" -bool true

if ! defaults read /Library/Preferences/com.apple.loginwindow.plist LoginwindowText > /dev/null; then
    sudo defaults write /Library/Preferences/com.apple.loginwindow.plist LoginwindowText -string "This computer belongs to @lstoll. Please call +1 216 505 1155 if found."
fi

if [ `defaults read /Library/Preferences/com.apple.loginwindow.plist GuestEnabled` == "1" ]; then
    sudo defaults write /Library/Preferences/com.apple.loginwindow.plist GuestEnabled -bool NO
fi

defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

if [ ! -f /usr/local/bin/brew ]; then
    echo "--> Installing Homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "--> Running brew bundle"
brew bundle

echo "--> Setting up go things"
go get -u github.com/alecthomas/gometalinter
gometalinter --install
go get -u github.com/kardianos/govendor
go get -u github.com/rogpeppe/godef
go get -u github.com/nsf/gocode
go get -u golang.org/x/tools/cmd/gorename
go get -u golang.org/x/tools/cmd/guru

echo "--> Setting up hg things"
if [ ! -d "$HOME/Library/Python/2.7/lib/python/site-packages/keyring" ]; then
    pip install --user keyring
    pip install --user mercurial_keyring
fi
if [ ! -d "$HOME/Library/Python/2.7/lib/python/site-packages/hggit" ]; then 
    pip install --user hg-git
fi
