#!/bin/bash
set -euo pipefail

if [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
fi

if [ -f /etc/os-release ]; then
    . /etc/os-release
fi

# TODO - why do we have to do this.
function finish {
    if [ -f ~/.netrc.tmp ]; then
        mv ~/.netrc.tmp ~/.netrc
    fi
}
trap finish EXIT
if [ -f ~/.netrc ]; then
    echo "--> Temporarily relocating netrc"
    mv ~/.netrc ~/.netrc.tmp
fi

if [ ! -f /usr/bin/ansible-playbook ]; then
#    if [ "$ID" == "debian" ]; then
        #sudo apt-get install -y software-properties-common
        #sudo apt-add-repository -y ppa:ansible/ansible
    #fi
    sudo apt-get update
    sudo apt-get install -y ansible
fi

#sudo ansible-playbook -i "$(hostname)," -c local playbook.yml
sudo ansible-playbook -i inventory --limit $(hostname) playbook.yml

rm -f playbook.retry
