#!/usr/bin/env bash

if [ ! -f ".script/travis-build-${BUILD}" ]; then
    echo "--> Error! No build script for ${BUILD}"
    exit 1
fi

echo "--> Building for ${BUILD}"
".script/travis-build-${BUILD}"
