#!/usr/bin/env bash

echo "--> Bootstrapping emacs"
sudo add-apt-repository -y ppa:cassou/emacs &&
    sudo apt-get -qq update &&
    sudo apt-get -qq -f install &&
    sudo apt-get -qq install emacs24 emacs24-el;

echo "--> Running emacs"
export HOME=$TRAVIS_BUILD_DIR
emacs --batch -l "$HOME/.emacs.d/init.el"
