- name: SSH unlock enc FS
  apt:
    name: dropbear-initramfs
    state: latest
  register: apt_dropbear_initramfs

- name: Re-use existing host keys
  command: /usr/lib/dropbear/dropbearconvert openssh dropbear /etc/ssh/ssh_host_{{item}}_key /etc/dropbear-initramfs/dropbear_{{item}}_host_key
  with_items:
    - rsa
    - ecdsa
  register: host_keys
  when: apt_dropbear_initramfs.changed

- name: remote SSH unlock keys
  template:
    src: authorized_keys.j2
    dest: /etc/dropbear-initramfs/authorized_keys
    owner: root
    mode: 0644
  register: dropbear_keys

- name: Update initramfs
  command: update-initramfs -u
  when: dropbear_keys.changed or host_keys.changed
